services:
  app:
    build:
      context: .
      target: jre-distroless 
    hostname: bot-service
    ports:
      - "8080:8080"
    env_file:
        - dev.env
    profiles:
      - app
    depends_on:
      database:
        condition: service_healthy
      discovery:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./internal
  database:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5435:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "db"]
        timeout: 5s
        retries: 10
  discovery:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    profiles:
      - app
      - discovery
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      timeout: 3s
      retries: 10