application:
  bot:
    cool-down: 1s
    update-freq: 15s
spring:
  application:
    name: bot-service
  datasource:
    host: localhost
    port: 5435
    database: db
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: user
    password: password
server:
  port: 8080
  error:
    include-stacktrace: never
